// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcBrr3ZmsQ_MkCeJpuDudVm_U8f5diT4',
    appId: '1:665270910955:web:5e2b5df4f3d7070feb23ae',
    messagingSenderId: '665270910955',
    projectId: 'nectar-5294a',
    authDomain: 'nectar-5294a.firebaseapp.com',
    storageBucket: 'nectar-5294a.firebasestorage.app',
    measurementId: 'G-HQK62DCV9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXevK09S24HiAHuqsMz-x66Enlg_t31O4',
    appId: '1:665270910955:android:ba9a1df018aec47feb23ae',
    messagingSenderId: '665270910955',
    projectId: 'nectar-5294a',
    storageBucket: 'nectar-5294a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj24GfjsjWpT1GrcwyIN0MLYjOd9U-pcA',
    appId: '1:665270910955:ios:8bea429294a76a55eb23ae',
    messagingSenderId: '665270910955',
    projectId: 'nectar-5294a',
    storageBucket: 'nectar-5294a.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj24GfjsjWpT1GrcwyIN0MLYjOd9U-pcA',
    appId: '1:665270910955:ios:8bea429294a76a55eb23ae',
    messagingSenderId: '665270910955',
    projectId: 'nectar-5294a',
    storageBucket: 'nectar-5294a.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgcBrr3ZmsQ_MkCeJpuDudVm_U8f5diT4',
    appId: '1:665270910955:web:5a63b11252913007eb23ae',
    messagingSenderId: '665270910955',
    projectId: 'nectar-5294a',
    authDomain: 'nectar-5294a.firebaseapp.com',
    storageBucket: 'nectar-5294a.firebasestorage.app',
    measurementId: 'G-1LNFZ1PJ2J',
  );
}
